/**
 * Generic sticker-pack image renderer.
 *
 * Stickers live in public/emoji/gif/ (bundled to dist/emoji/gif/ and unpacked
 * to app.asar.unpacked/dist/emoji/gif/ in the packaged app). They are NOT
 * emoji-codepoint based — they carry arbitrary filenames (e.g. Telegram-style
 * "AgAD....webp"). The list of valid filenames is generated by
 * scripts/gen-emoji-assets.mjs into src/emoji/sticker_pack.json.
 */
import React from 'react'

declare global {
  interface Window {
    addAPI?: {
      resourcesPath?: string
      isPackaged?: boolean
    }
  }
}

interface StickerImgProps {
  filename: string
  size?: number
  className?: string
}

export const StickerImg: React.FC<StickerImgProps> = ({ filename, size = 48, className = '' }) => {
  // Resolve sticker URL for both dev and packaged modes
  // In Electron, use addAPI.resourcesPath (/resources in unpacked dir)
  // The stickers are unpacked to /resources/app.asar.unpacked/dist/emoji/gif/
  let src: string
  if (typeof window !== 'undefined' && window.addAPI) {
    const rp = window.addAPI.resourcesPath
    // Packaged Electron: resourcesPath = <app>/resources
    // Stickers are at <resources>/app.asar.unpacked/dist/emoji/gif/
    if (rp && typeof rp === 'string') {
      src = `file://${rp}/app.asar.unpacked/dist/emoji/gif/${filename}`
    } else {
      src = `/emoji/gif/${filename}`
    }
  } else {
    // Dev mode or SSR
    src = `/emoji/gif/${filename}`
  }

  return (
    <img
      src={src}
      alt={filename}
      style={{ width: size, height: size, objectFit: 'contain', verticalAlign: 'middle' }}
      className={`sticker-img ${className}`}
    />
  )
}