/**
 * Generic sticker-pack image renderer.
 *
 * Stickers live in public/emoji/gif/ (bundled to dist/emoji/gif/ and unpacked
 * to app.asar.unpacked/dist/emoji/gif/ in the packaged app). They are NOT
 * emoji-codepoint based — they carry arbitrary filenames (e.g. Telegram-style
 * "AgAD....webp"). The list of valid filenames is generated by
 * scripts/gen-emoji-assets.mjs into src/emoji/sticker_pack.json.
 *
 * Loading strategy: prefer a base64 data URL from the preload's readAsset (works
 * in both dev and packaged modes, sidesteps any file:// CSP/path quirks), and
 * fall back to a direct URL otherwise.
 */
import React, { useEffect, useState } from 'react'

function stickerUrl(filename: string): string {
  const resourcesPath = typeof window !== 'undefined' && window.addAPI?.resourcesPath
  const isPackaged = typeof window !== 'undefined' && window.addAPI?.isPackaged === true
  if (isPackaged && resourcesPath) {
    return `file://${resourcesPath}/app.asar.unpacked/dist/emoji/gif/${filename}`
  }
  return `/emoji/gif/${filename}`
}

interface StickerImgProps {
  filename: string
  size?: number
  className?: string
}

export const StickerImg: React.FC<StickerImgProps> = ({ filename, size = 48, className = '' }) => {
  const [src, setSrc] = useState<string | null>(null)

  useEffect(() => {
    let cancelled = false
    const dataUrl = window.addAPI?.readAsset?.(`emoji/gif/${filename}`)
    if (dataUrl && !cancelled) {
      setSrc(dataUrl)
    } else if (!cancelled) {
      setSrc(stickerUrl(filename))
    }
    return () => {
      cancelled = true
    }
  }, [filename])

  if (!src) return <span style={{ width: size, height: size, display: 'inline-block' }} />
  return (
    <img
      src={src}
      alt={filename}
      style={{ width: size, height: size, objectFit: 'contain', verticalAlign: 'middle' }}
      className={`sticker-img ${className}`}
    />
  )
}

export { stickerUrl }
